"""stamp user

Revision ID: 303d047d8a14
Revises: c2760b40408d
Create Date: 2022-07-13 17:40:57.534350

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '303d047d8a14'
down_revision = 'c2760b40408d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('image_labels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rating_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_index('fk_image_labels_images_id_images')
        batch_op.create_foreign_key(batch_op.f('fk_image_labels_user_id_rate_users'), 'rate_users', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_image_labels_images_id_images'), 'images', ['images_id'], ['id'])
        batch_op.drop_column('rating')

    with op.batch_alter_table('rate_users', schema=None) as batch_op:
        batch_op.drop_index('fk_rate_users_role_id_roles')
        batch_op.create_foreign_key(batch_op.f('fk_rate_users_role_id_roles'), 'roles', ['role_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('image_labels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_image_labels_images_id_images'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_image_labels_user_id_rate_users'), type_='foreignkey')
        batch_op.create_index('fk_image_labels_images_id_images', ['images_id'], unique=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('rating_score')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
