"""Change user to Rateusers

Revision ID: c2760b40408d
Revises: 8feb1670ee7f
Create Date: 2022-07-13 11:10:01.467077

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c2760b40408d'
down_revision = '8feb1670ee7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('organization', sa.String(length=64), nullable=True),
    sa.Column('change_code_hash', sa.String(length=128), nullable=True),
    sa.Column('change_code_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_rate_users_role_id_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rate_users'))
    )
    with op.batch_alter_table('rate_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rate_users_email'), ['email'], unique=True)

    op.drop_table('users')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('users',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='latin1_spanish_ci', length=64), nullable=True),
    sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('confirmed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('first_name', mysql.VARCHAR(collation='latin1_spanish_ci', length=64), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(collation='latin1_spanish_ci', length=64), nullable=True),
    sa.Column('organization', mysql.VARCHAR(collation='latin1_spanish_ci', length=64), nullable=True),
    sa.Column('change_code_hash', mysql.VARCHAR(collation='latin1_spanish_ci', length=128), nullable=True),
    sa.Column('change_code_time', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('password_hash', mysql.VARCHAR(collation='latin1_spanish_ci', length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_spanish_ci',
    mysql_default_charset='latin1',
    mysql_engine='MyISAM'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('fk_users_role_id_roles', ['role_id'], unique=False)

    op.drop_table('rate_users')
    # ### end Alembic commands ###
